---
mysql_homeassistant_db: homeassistant
mysql_databases:
  - name: "{{ mysql_homeassistant_db }}"
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: homeassistant
    host: "%"
    password: "{{ msyql_homeassistant_password }}"
    priv: "{{ mysql_homeassistant_db }}.*:ALL"