- name: Install requirements
  apt:
    name: software-properties-common
    state: present

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 379CE192D401AB61

- name: Install Tvheadend Bintray repository
  apt_repository:
    repo: deb https://dl.bintray.com/tvheadend/deb xenial stable

- name: Install tvheadend
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - tvheadend

