- name: Add bash_profile file
  file:
    dest: "/home/{{ item.user }}/.bash_profile"
    state: touch
    owner: "{{ item.user }}"
  with_items: "{{ user_prompts}} "

- name: Test for line
  shell: /bin/grep "export PS1=" /home/{{ item.user }}/.bash_profile
  register: test_grep
  failed_when: test_grep.rc not in [1, 0]
  with_items: "{{ user_prompts}} "

- name: add prompt config to bash_profile
  lineinfile:
    dest: /home/{{ item.1.user }}/.bash_profile
    state: present
    line: 'export PS1="{{ item.1.pattern }}"'
  when: test_grep.results[item.0].stdout == ""
  with_indexed_items: "{{ user_prompts}} "

- name: add prompt config to bash_profile
  lineinfile:
    dest: /home/{{ item.1.user }}/.bash_profile
    state: present
    line: 'export PS1="{{ item.1.pattern }}"'
    regexp: 'export PS1='
  when: test_grep.results[item.0].stdout != ""
  with_indexed_items: "{{ user_prompts}} "